// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickBite.Data;

#nullable disable

namespace QuickBite.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728120414_dung_InitialOrderCoreV2")]
    partial class dung_InitialOrderCoreV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickBite.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Chủ quán QuickBite",
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEJFpZ+ufTGXPh6BKlRvKjXzXADutxFQ/qwL568hK7uH0t/S5bWeEtmfzhiKXcqSkmQ==",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Quản lý ca",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEGoFiVYx+Wgwqn9m1YSLrJInS2af1iMHtb562Y6KK6PBi8Kvcx4O+jkzHjmuTrMHtQ==",
                            Role = 4,
                            Username = "manager"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nhân viên nhận đơn",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEHV+SCr2GoiocJowWlig57BqENDkrmrIWMuoiEouQVJPh8bbpDB8OCom/sEpf+35QA==",
                            Role = 1,
                            Username = "staff"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Bếp",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEK9k5yyJ+GUBVAWApffAO0aTAaX3TdQPaLkwKkbTK6tDKVVrMIvVLZQwpvccTnj7lw==",
                            Role = 2,
                            Username = "kitchen"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Shipper",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEHWoZzeZv3ASHpz5XL84pUUBylB35RExme6xcmoUjnRoftIvgEx90xcppMehskjnqg==",
                            Role = 3,
                            Username = "shipper"
                        });
                });

            modelBuilder.Entity("QuickBite.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các món cơm phần đầy đặn",
                            DisplayOrder = 1,
                            Name = "Cơm"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Món nước truyền thống",
                            DisplayOrder = 2,
                            Name = "Phở & Bún"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Món ăn chơi, ăn kèm",
                            DisplayOrder = 3,
                            Name = "Ăn vặt"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Giải khát, cà phê, trà",
                            DisplayOrder = 4,
                            Name = "Đồ uống"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chè, bánh ngọt, kem",
                            DisplayOrder = 5,
                            Name = "Tráng miệng"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Thanh đạm, phù hợp ngày rằm - mùng 1",
                            DisplayOrder = 6,
                            Name = "Món chay"
                        });
                });

            modelBuilder.Entity("QuickBite.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sườn nướng than, bì, chả trứng, mỡ hành, nước mắm chua ngọt",
                            ImageUrl = "https://picsum.photos/seed/comtam/400/300",
                            IsAvailable = true,
                            Name = "Cơm tấm sườn bì chả",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đùi gà da giòn xối mỡ tỏi, cơm chiên nghệ, dưa leo",
                            ImageUrl = "https://picsum.photos/seed/comga/400/300",
                            IsAvailable = true,
                            Name = "Cơm gà xối mỡ",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cơm chiên trứng, lạp xưởng, đậu que, cà rốt",
                            ImageUrl = "https://picsum.photos/seed/comchien/400/300",
                            IsAvailable = true,
                            Name = "Cơm chiên dương châu",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bò mềm xào lúc lắc ớt chuông, khoai tây chiên ăn kèm",
                            ImageUrl = "https://picsum.photos/seed/boluclac/400/300",
                            IsAvailable = true,
                            Name = "Cơm bò lúc lắc",
                            Price = 55000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sườn cốt lết ướp mật ong nướng, kim chi cải thảo",
                            ImageUrl = "https://picsum.photos/seed/suonmatong/400/300",
                            IsAvailable = true,
                            Name = "Cơm sườn nướng mật ong",
                            Price = 48000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước dùng hầm xương 8 tiếng, bò tái mềm, bánh phở tươi",
                            ImageUrl = "https://picsum.photos/seed/phobo/400/300",
                            IsAvailable = true,
                            Name = "Phở bò tái",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gà ta xé, nước dùng thanh, hành lá gừng thái sợi",
                            ImageUrl = "https://picsum.photos/seed/phoga/400/300",
                            IsAvailable = true,
                            Name = "Phở gà",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cay chuẩn vị Huế, giò heo, chả cua, rau sống đầy đủ",
                            ImageUrl = "https://picsum.photos/seed/bunbo/400/300",
                            IsAvailable = true,
                            Name = "Bún bò Huế",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chả nướng than hoa, bún rối, nước chấm đu đủ xanh",
                            ImageUrl = "https://picsum.photos/seed/buncha/400/300",
                            IsAvailable = false,
                            Name = "Bún chả Hà Nội",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thịt nướng sả, chả giò, đồ chua, đậu phộng rang",
                            ImageUrl = "https://picsum.photos/seed/bunthitnuong/400/300",
                            IsAvailable = true,
                            Name = "Bún thịt nướng",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Da giòn rụm, ướp 12 loại gia vị, kèm tương ớt",
                            ImageUrl = "https://picsum.photos/seed/garan/400/300",
                            IsAvailable = true,
                            Name = "Gà rán giòn (2 miếng)",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khoai chiên hai lửa giòn lâu, rắc phô mai tùy chọn",
                            ImageUrl = "https://picsum.photos/seed/khoaitay/400/300",
                            IsAvailable = true,
                            Name = "Khoai tây chiên",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh mì nóng, thịt nướng, pate, đồ chua, rau thơm",
                            ImageUrl = "https://picsum.photos/seed/banhmi/400/300",
                            IsAvailable = true,
                            Name = "Bánh mì thịt nướng",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nem truyền thống nhân thịt mộc nhĩ, chấm mắm chua ngọt",
                            ImageUrl = "https://picsum.photos/seed/nemran/400/300",
                            IsAvailable = true,
                            Name = "Nem rán (5 cái)",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bò viên, cá viên, đậu bắp cuộn — 6 xiên nướng sốt me",
                            ImageUrl = "https://picsum.photos/seed/xienque/400/300",
                            IsAvailable = true,
                            Name = "Xiên que thập cẩm",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trà đen ủ lạnh, đào ngâm, cam vàng, sả tươi",
                            ImageUrl = "https://picsum.photos/seed/tradao/400/300",
                            IsAvailable = true,
                            Name = "Trà đào cam sả",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cà phê phin robusta đậm, sữa đặc",
                            ImageUrl = "https://picsum.photos/seed/caphe/400/300",
                            IsAvailable = true,
                            Name = "Cà phê sữa đá",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cam sành vắt nguyên chất, không đường tùy chọn",
                            ImageUrl = "https://picsum.photos/seed/nuoccam/400/300",
                            IsAvailable = true,
                            Name = "Nước cam ép",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trân châu đường đen nấu mỗi 2 giờ, trà ô long",
                            ImageUrl = "https://picsum.photos/seed/trasua/400/300",
                            IsAvailable = true,
                            Name = "Trà sữa trân châu",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lon 330ml ướp lạnh",
                            ImageUrl = "https://picsum.photos/seed/coca/400/300",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khúc bạch phô mai, nhãn, hạnh nhân lát",
                            ImageUrl = "https://picsum.photos/seed/chekhucbach/400/300",
                            IsAvailable = true,
                            Name = "Chè khúc bạch",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flan trứng sữa mềm mịn, caramel đắng nhẹ",
                            ImageUrl = "https://picsum.photos/seed/banhflan/400/300",
                            IsAvailable = true,
                            Name = "Bánh flan",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rau câu nước dừa tươi, lớp cốt dừa béo",
                            ImageUrl = "https://picsum.photos/seed/raucau/400/300",
                            IsAvailable = true,
                            Name = "Rau câu dừa",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nếp cẩm dẻo thơm, sữa chua nhà làm",
                            ImageUrl = "https://picsum.photos/seed/nepcam/400/300",
                            IsAvailable = true,
                            Name = "Sữa chua nếp cẩm",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kem dừa trong trái dừa tươi, đậu phộng, mứt",
                            ImageUrl = "https://picsum.photos/seed/kemdua/400/300",
                            IsAvailable = false,
                            Name = "Kem dừa",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đậu hũ, nấm, rau củ kho, canh rong biển",
                            ImageUrl = "https://picsum.photos/seed/comchay/400/300",
                            IsAvailable = true,
                            Name = "Cơm chay thập cẩm",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Riêu đậu hũ nấm, cà chua, đậu rán",
                            ImageUrl = "https://picsum.photos/seed/bunrieuchay/400/300",
                            IsAvailable = true,
                            Name = "Bún riêu chay",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đậu hũ non chiên sốt cà chua, hành lá",
                            ImageUrl = "https://picsum.photos/seed/dauhusotca/400/300",
                            IsAvailable = true,
                            Name = "Đậu hũ sốt cà",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cuốn rau củ, bún, đậu hũ; chấm tương đậu phộng",
                            ImageUrl = "https://picsum.photos/seed/goicuonchay/400/300",
                            IsAvailable = true,
                            Name = "Gỏi cuốn chay (3 cuốn)",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nấm bào ngư xào sả ớt cay nhẹ, ăn kèm cơm trắng",
                            ImageUrl = "https://picsum.photos/seed/namxao/400/300",
                            IsAvailable = true,
                            Name = "Nấm xào sả ớt",
                            Price = 30000m
                        });
                });

            modelBuilder.Entity("QuickBite.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcceptedByAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByAccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QuickBite.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("QuickBite.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByAccountId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("QuickBite.Models.PhoneBlacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("PhoneBlacklists");
                });

            modelBuilder.Entity("QuickBite.Models.ReasonCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ReasonCatalogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Kind = 0,
                            Text = "Hết nguyên liệu"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Kind = 0,
                            Text = "Ngoài phạm vi giao"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Kind = 0,
                            Text = "Quán quá tải"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Kind = 0,
                            Text = "Nghi ngờ đơn ảo"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            IsActive = true,
                            Kind = 1,
                            Text = "Đặt nhầm"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 2,
                            IsActive = true,
                            Kind = 1,
                            Text = "Đổi ý không đặt nữa"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 3,
                            IsActive = true,
                            Kind = 1,
                            Text = "Chờ quá lâu"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            IsActive = true,
                            Kind = 2,
                            Text = "Khách không nghe máy"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 2,
                            IsActive = true,
                            Kind = 2,
                            Text = "Địa chỉ sai hoặc không tìm thấy"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 3,
                            IsActive = true,
                            Kind = 2,
                            Text = "Khách từ chối nhận hàng"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            IsActive = true,
                            Kind = 3,
                            Text = "Khách không đến lấy"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 2,
                            IsActive = true,
                            Kind = 3,
                            Text = "Không liên lạc được với khách"
                        });
                });

            modelBuilder.Entity("QuickBite.Models.WorkSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CheckInAt");

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("QuickBite.Models.MenuItem", b =>
                {
                    b.HasOne("QuickBite.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QuickBite.Models.Order", b =>
                {
                    b.HasOne("QuickBite.Models.Account", "AcceptedByAccount")
                        .WithMany()
                        .HasForeignKey("AcceptedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptedByAccount");
                });

            modelBuilder.Entity("QuickBite.Models.OrderItem", b =>
                {
                    b.HasOne("QuickBite.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickBite.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QuickBite.Models.OrderStatusHistory", b =>
                {
                    b.HasOne("QuickBite.Models.Account", "ChangedByAccount")
                        .WithMany()
                        .HasForeignKey("ChangedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuickBite.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByAccount");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QuickBite.Models.WorkSession", b =>
                {
                    b.HasOne("QuickBite.Models.Account", "Account")
                        .WithMany("WorkSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QuickBite.Models.Account", b =>
                {
                    b.Navigation("WorkSessions");
                });

            modelBuilder.Entity("QuickBite.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("QuickBite.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QuickBite.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
